language: node_js
node_js:
  - "6"

install:
- npm install -g angular-cli
- npm install -g karma
- npm install

before_script:
- ng build
- ng serve &

script: ng lint && ng test --watch=false && ng e2e
