language: node_js
node_js:
  - "6"

install:
  - npm install -g angular-cli@webpack
  - npm install -g karma
  - npm install

before_script:
  - npm run pree2e
  - ng serve --env=ci &
  - sleep 30

script:
  - ng lint
  - ng test --watch false
  - node_modules/protractor/bin/protractor ./protractor.conf.js

before_deploy:
  - npm run package

deploy:
    edge: true
    provider: cloudfoundry
    api: https://api.run.pez.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: pivot-jsharpe
    space: known-for
    manifest: manifest.yml
