language: node_js
node_js:
  - "6"

install:
  - npm install -g angular-cli
  - npm install -g karma
  - npm install

before_script:
  - ng -v
  - npm run pree2e
  - ng serve --env=ci &
  - sleep 30

script:
  - ng lint
  - ng test --no-watch
  - npm run endtoend

before_deploy:
  - npm run package

deploy:
    edge:
      branch: cf-login
    provider: cloudfoundry
    api: https://api.run.pez.pivotal.io
    username: $CF_USERNAME
    password: $CF_PASSWORD
    organization: pivot-jsharpe
    space: known-for
    manifest: manifest.yml
