dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - "6"

install:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ng -v

script:
  - ng lint
  - ng test --no-watch --code-coverage
  - npm run cie2e

after_success:
  - npm run coveralls

before_deploy:
  - npm run package

deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pez.pivotal.io
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: pivot-jsharpe
  space: known-for
  manifest: manifest.yml
